version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: nihongo_sr
    restart: always
    environment:
      POSTGRES_USER: nihongo_sr_user
      POSTGRES_PASSWORD: nihongo_sr_password
      POSTGRES_DB: nihongo_sr_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
