import { KanjiData } from 'src/types/kanjiData.type';

export const KanjiSeedData: KanjiData[] = [
  {
    kanji: '安',
    kun_reading: ['やすい'],
    on_reading: ['アン'],
    han_viet: 'AN',
    meaning_vi: 'Bình an, an toàn, rẻ',
    meaning_en: 'Peaceful, safe, cheap',
    radicals: '宀',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: 'この店は安いです。',
        reading: 'このみせはやすいです。',
        meaning_vi: 'Cửa hàng này rẻ.',
        meaning_en: 'This shop is cheap.',
      },
      {
        sentence: '安全な場所を探してください。',
        reading: 'あんぜんなばしょをさがしてください。',
        meaning_vi: 'Hãy tìm một nơi an toàn.',
        meaning_en: 'Please find a safe place.',
      },
    ],
  },
  {
    kanji: '一',
    kun_reading: ['ひとつ'],
    on_reading: ['イチ', 'イツ'],
    han_viet: 'NHẤT',
    meaning_vi: 'Một',
    meaning_en: 'One',
    radicals: '一',
    strokes: 1,
    level: 'N5',
    examples: [
      {
        sentence: 'リンゴを一つください。',
        reading: 'りんごをひとつください。',
        meaning_vi: 'Cho tôi một quả táo.',
        meaning_en: 'Please give me one apple.',
      },
      {
        sentence: '一日中勉強しました。',
        reading: 'いちにちじゅうべんきょうしました。',
        meaning_vi: 'Tôi đã học suốt cả ngày.',
        meaning_en: 'I studied all day long.',
      },
    ],
  },
  {
    kanji: '飲',
    kun_reading: ['のむ'],
    on_reading: ['イン'],
    han_viet: 'ẨM',
    meaning_vi: 'Uống',
    meaning_en: 'Drink',
    radicals: '食',
    strokes: 12,
    level: 'N5',
    examples: [
      {
        sentence: '水を飲みます。',
        reading: 'みずをのみます。',
        meaning_vi: 'Tôi uống nước.',
        meaning_en: 'I drink water.',
      },
      {
        sentence: '毎朝コーヒーを飲みます。',
        reading: 'まいあさコーヒーをのみます。',
        meaning_vi: 'Tôi uống cà phê mỗi sáng.',
        meaning_en: 'I drink coffee every morning.',
      },
    ],
  },
  {
    kanji: '右',
    kun_reading: ['みぎ'],
    on_reading: ['ウ', 'ユウ'],
    han_viet: 'HỮU',
    meaning_vi: 'Bên phải',
    meaning_en: 'Right',
    radicals: '口',
    strokes: 5,
    level: 'N5',
    examples: [
      {
        sentence: '右を見てください。',
        reading: 'みぎをみてください。',
        meaning_vi: 'Hãy nhìn sang phải.',
        meaning_en: 'Please look to the right.',
      },
      {
        sentence: '右手で書きます。',
        reading: 'みぎてでかきます。',
        meaning_vi: 'Tôi viết bằng tay phải.',
        meaning_en: 'I write with my right hand.',
      },
    ],
  },
  {
    kanji: '雨',
    kun_reading: ['あめ'],
    on_reading: ['ウ'],
    han_viet: 'VŨ',
    meaning_vi: 'Mưa',
    meaning_en: 'Rain',
    radicals: '雨',
    strokes: 8,
    level: 'N5',
    examples: [
      {
        sentence: '今日は雨が降っています。',
        reading: 'きょうはあめがふっています。',
        meaning_vi: 'Hôm nay trời đang mưa.',
        meaning_en: "It's raining today.",
      },
      {
        sentence: '雨の日は家で映画を見ます。',
        reading: 'あめのひはいえでえいがをみます。',
        meaning_vi: 'Vào ngày mưa tôi xem phim ở nhà.',
        meaning_en: 'On rainy days, I watch movies at home.',
      },
    ],
  },
  {
    kanji: '駅',
    kun_reading: [],
    on_reading: ['えき'],
    han_viet: 'DỊCH',
    meaning_vi: 'ga',
    meaning_en: 'station',
    radicals: '馬',
    strokes: 14,
    level: 'N5',
    examples: [
      {
        sentence: '駅に着きました。',
        reading: 'えきにつきました。',
        meaning_vi: 'Tôi đã đến ga.',
        meaning_en: 'I have arrived at the station.',
      },
      {
        sentence: '駅員が案内してくれました。',
        reading: 'えきいんがあんないしてくれました。',
        meaning_vi: 'Nhân viên nhà ga đã hướng dẫn tôi.',
        meaning_en: 'The station staff guided me.',
      },
    ],
  },
  {
    kanji: '円',
    kun_reading: ['まる.い'],
    on_reading: ['えん'],
    han_viet: 'VIÊN',
    meaning_vi: 'đồng yên, tròn',
    meaning_en: 'yen, round',
    radicals: '冂',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '百円を持っています。',
        reading: 'ひゃくえんをもっています。',
        meaning_vi: 'Tôi có 100 yên.',
        meaning_en: 'I have 100 yen.',
      },
      {
        sentence: '円いテーブルを買いました。',
        reading: 'まるいテーブルをかいました。',
        meaning_vi: 'Tôi đã mua một cái bàn tròn.',
        meaning_en: 'I bought a round table.',
      },
    ],
  },
  {
    kanji: '火',
    kun_reading: ['ひ'],
    on_reading: ['か'],
    han_viet: 'HỎA',
    meaning_vi: 'lửa, hỏa',
    meaning_en: 'fire',
    radicals: '火',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '火をつけないでください。',
        reading: 'ひをつけないでください。',
        meaning_vi: 'Xin đừng đốt lửa.',
        meaning_en: 'Please do not light a fire.',
      },
      {
        sentence: '火曜日は忙しいです。',
        reading: 'かようびはいそがしいです。',
        meaning_vi: 'Thứ ba tôi bận.',
        meaning_en: 'Tuesday is busy for me.',
      },
    ],
  },
  {
    kanji: '花',
    kun_reading: ['はな'],
    on_reading: ['か'],
    han_viet: 'HOA',
    meaning_vi: 'hoa',
    meaning_en: 'flower',
    radicals: '艹',
    strokes: 7,
    level: 'N5',
    examples: [
      {
        sentence: 'この花はきれいです。',
        reading: 'このはなはきれいです。',
        meaning_vi: 'Bông hoa này đẹp.',
        meaning_en: 'This flower is beautiful.',
      },
      {
        sentence: '春に花が咲きます。',
        reading: 'はるにはながさきます。',
        meaning_vi: 'Hoa nở vào mùa xuân.',
        meaning_en: 'Flowers bloom in spring.',
      },
    ],
  },
  {
    kanji: '下',
    kun_reading: ['した', 'さ.げる', 'お.ろす', 'く.だる'],
    on_reading: ['か', 'げ'],
    han_viet: 'HẠ',
    meaning_vi: 'dưới, phía dưới, hạ/xuống',
    meaning_en: 'down, below',
    radicals: '一',
    strokes: 3,
    level: 'N5',
    examples: [
      {
        sentence: '机の下に猫がいます。',
        reading: 'つくえのしたにねこがいます。',
        meaning_vi: 'Có một con mèo dưới bàn.',
        meaning_en: 'There is a cat under the desk.',
      },
      {
        sentence: '階段を下ります。',
        reading: 'かいだんをおります。',
        meaning_vi: 'Tôi đi xuống cầu thang.',
        meaning_en: 'I go down the stairs.',
      },
    ],
  },
  {
    kanji: '何',
    kun_reading: ['なに', 'なん'],
    on_reading: ['か'],
    han_viet: 'HÀ',
    meaning_vi: 'cái gì/cái nào',
    meaning_en: 'what',
    radicals: '亻',
    strokes: 7,
    level: 'N5',
    examples: [
      {
        sentence: '何を食べますか？',
        reading: 'なにをたべますか？',
        meaning_vi: 'Bạn ăn gì?',
        meaning_en: 'What do you eat?',
      },
      {
        sentence: '何時に起きますか？',
        reading: 'なんじにおきますか？',
        meaning_vi: 'Bạn thức dậy lúc mấy giờ?',
        meaning_en: 'What time do you wake up?',
      },
    ],
  },
  {
    kanji: '会',
    kun_reading: ['あ.う'],
    on_reading: ['かい', 'え'],
    han_viet: 'HỘI',
    meaning_vi: 'gặp gỡ, hội họp',
    meaning_en: 'meeting',
    radicals: '人',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: '友達と会いました。',
        reading: 'ともだちとあいました。',
        meaning_vi: 'Tôi đã gặp bạn.',
        meaning_en: 'I met my friend.',
      },
      {
        sentence: '会社で働いています。',
        reading: 'かいしゃではたらいています。',
        meaning_vi: 'Tôi làm việc ở công ty.',
        meaning_en: 'I work at a company.',
      },
    ],
  },
  {
    kanji: '外',
    kun_reading: ['そと', 'ほか', 'はず.れる', 'はず.す'],
    on_reading: ['がい', 'げ'],
    han_viet: 'NGOẠI',
    meaning_vi: 'ngoài, khác, tách rời ra',
    meaning_en: 'outside, external',
    radicals: '夕',
    strokes: 5,
    level: 'N5',
    examples: [
      {
        sentence: '外で遊びます。',
        reading: 'そとであそびます。',
        meaning_vi: 'Tôi chơi ở ngoài.',
        meaning_en: 'I play outside.',
      },
    ],
  },
  {
    kanji: '学',
    kun_reading: ['まな.ぶ'],
    on_reading: ['がく'],
    han_viet: 'HỌC',
    meaning_vi: 'học, khoa học, trường học',
    meaning_en: 'study, school',
    radicals: '子',
    strokes: 8,
    level: 'N5',
    examples: [
      {
        sentence: '学校に行きます。',
        reading: 'がっこうにいきます。',
        meaning_vi: 'Tôi đi đến trường.',
        meaning_en: 'I go to school.',
      },
    ],
  },
  {
    kanji: '間',
    kun_reading: ['あいだ'],
    on_reading: ['かん', 'けん'],
    han_viet: 'GIAN',
    meaning_vi: 'thời gian, khoảng thời gian',
    meaning_en: 'time, interval',
    radicals: '門',
    strokes: 12,
    level: 'N5',
    examples: [
      {
        sentence: '時間がありません。',
        reading: 'じかんがありません。',
        meaning_vi: 'Tôi không có thời gian.',
        meaning_en: 'I have no time.',
      },
      {
        sentence: '昼間は暖かいです。',
        reading: 'ひるまはあたたかいです。',
        meaning_vi: 'Ban ngày thì ấm áp.',
        meaning_en: 'It is warm during the daytime.',
      },
    ],
  },
  {
    kanji: '気',
    kun_reading: [],
    on_reading: ['き', 'け'],
    han_viet: 'KHÍ',
    meaning_vi: 'tinh thần, tâm trạng',
    meaning_en: 'spirit, mood',
    radicals: '气',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: '元気ですか？',
        reading: 'げんきですか？',
        meaning_vi: 'Bạn khỏe không?',
        meaning_en: 'How are you?',
      },
      {
        sentence: '天気がいいですね。',
        reading: 'てんきがいいですね。',
        meaning_vi: 'Thời tiết đẹp nhỉ.',
        meaning_en: "The weather is nice, isn't it?",
      },
    ],
  },
  {
    kanji: '九',
    kun_reading: ['ここの.つ'],
    on_reading: ['きゅう', 'く'],
    han_viet: 'CỬU',
    meaning_vi: 'chín',
    meaning_en: 'nine',
    radicals: '乙',
    strokes: 2,
    level: 'N5',
    examples: [
      {
        sentence: '九月に日本へ行きます。',
        reading: 'くがつににほんへいきます。',
        meaning_vi: 'Tôi sẽ đi Nhật vào tháng 9.',
        meaning_en: 'I will go to Japan in September.',
      },
      {
        sentence: '九時に起きます。',
        reading: 'くじにおきます。',
        meaning_vi: 'Tôi thức dậy lúc 9 giờ.',
        meaning_en: 'I wake up at 9 o’clock.',
      },
    ],
  },
  {
    kanji: '休',
    kun_reading: ['やす.む'],
    on_reading: ['きゅう'],
    han_viet: 'HƯU',
    meaning_vi: 'nghỉ ngơi',
    meaning_en: 'rest',
    radicals: '亻',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: '今日は休みです。',
        reading: 'きょうはやすみです。',
        meaning_vi: 'Hôm nay là ngày nghỉ.',
        meaning_en: 'Today is a holiday.',
      },
      {
        sentence: '夏休みが始まります。',
        reading: 'なつやすみがはじまります。',
        meaning_vi: 'Kỳ nghỉ hè bắt đầu.',
        meaning_en: 'Summer vacation starts.',
      },
    ],
  },
  {
    kanji: '魚',
    kun_reading: ['さかな', 'うお'],
    on_reading: ['ぎょ'],
    han_viet: 'NGƯ',
    meaning_vi: 'cá',
    meaning_en: 'fish',
    radicals: '魚',
    strokes: 11,
    level: 'N5',
    examples: [
      {
        sentence: '魚を食べます。',
        reading: 'さかなをたべます。',
        meaning_vi: 'Tôi ăn cá.',
        meaning_en: 'I eat fish.',
      },
      {
        sentence: '金魚を飼っています。',
        reading: 'きんぎょをかっています。',
        meaning_vi: 'Tôi nuôi cá vàng.',
        meaning_en: 'I have a goldfish.',
      },
    ],
  },
  {
    kanji: '金',
    kun_reading: ['かね'],
    on_reading: ['きん', 'こん'],
    han_viet: 'KIM',
    meaning_vi: 'vàng, tiền',
    meaning_en: 'gold, money',
    radicals: '金',
    strokes: 8,
    level: 'N5',
    examples: [
      {
        sentence: 'お金を持っていますか？',
        reading: 'おかねをもっていますか？',
        meaning_vi: 'Bạn có tiền không?',
        meaning_en: 'Do you have money?',
      },
      {
        sentence: '金曜日に会いましょう。',
        reading: 'きんようびにあいましょう。',
        meaning_vi: 'Hãy gặp nhau vào thứ sáu.',
        meaning_en: "Let's meet on Friday.",
      },
    ],
  },
  {
    kanji: '空',
    kun_reading: ['そら', 'あ.ける', 'あ.く', 'から'],
    on_reading: ['くう'],
    han_viet: 'KHÔNG',
    meaning_vi: 'bầu trời, trống, chỗ trống',
    meaning_en: 'sky, empty',
    radicals: '穴',
    strokes: 8,
    level: 'N5',
    examples: [
      {
        sentence: '空が青いですね。',
        reading: 'そらがあおいですね。',
        meaning_vi: 'Bầu trời thật xanh.',
        meaning_en: 'The sky is blue.',
      },
      {
        sentence: '空港で待っています。',
        reading: 'くうこうでまっています。',
        meaning_vi: 'Tôi đang đợi ở sân bay.',
        meaning_en: 'I am waiting at the airport.',
      },
    ],
  },
  {
    kanji: '月',
    kun_reading: ['つき'],
    on_reading: ['げつ', 'がつ'],
    han_viet: 'NGUYỆT',
    meaning_vi: 'tháng, mặt trăng',
    meaning_en: 'moon, month',
    radicals: '月',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '月がきれいですね。',
        reading: 'つきがきれいですね。',
        meaning_vi: 'Mặt trăng đẹp nhỉ.',
        meaning_en: "The moon is beautiful, isn't it?",
      },
      {
        sentence: '来月旅行します。',
        reading: 'らいげつりょこうします。',
        meaning_vi: 'Tôi sẽ đi du lịch vào tháng sau.',
        meaning_en: 'I will travel next month.',
      },
    ],
  },
  {
    kanji: '見',
    kun_reading: ['み.る', 'み.える', 'み.せる'],
    on_reading: ['けん'],
    han_viet: 'KIẾN',
    meaning_vi: 'nhìn, ngắm, cho xem',
    meaning_en: 'see, look',
    radicals: '見',
    strokes: 7,
    level: 'N5',
    examples: [
      {
        sentence: '映画を見ました。',
        reading: 'えいがをみました。',
        meaning_vi: 'Tôi đã xem phim.',
        meaning_en: 'I watched a movie.',
      },
    ],
  },
  {
    kanji: '言',
    kun_reading: ['い.う', 'こと'],
    on_reading: ['げん', 'ごん'],
    han_viet: 'NGÔN',
    meaning_vi: 'từ ngữ, nói',
    meaning_en: 'words, speech',
    radicals: '言',
    strokes: 7,
    level: 'N5',
    examples: [
      {
        sentence: '彼は「ありがとう」と言いました。',
        reading: 'かれは「ありがとう」といいました。',
        meaning_vi: "Anh ấy đã nói 'cảm ơn'.",
        meaning_en: "He said 'thank you'.",
      },
      {
        sentence: '日本語の言葉を学ぶ。',
        reading: 'にほんごのことばをまなぶ。',
        meaning_vi: 'Học từ vựng tiếng Nhật.',
        meaning_en: 'Learn Japanese words.',
      },
    ],
  },
  {
    kanji: '古',
    kun_reading: ['ふる.い'],
    on_reading: ['こ'],
    han_viet: 'CỔ',
    meaning_vi: 'cũ, cổ',
    meaning_en: 'old, ancient',
    radicals: '口',
    strokes: 5,
    level: 'N5',
    examples: [
      {
        sentence: '古い本を読みます。',
        reading: 'ふるいほんをよみます。',
        meaning_vi: 'Tôi đọc sách cũ.',
        meaning_en: 'I read old books.',
      },
      {
        sentence: '古書を探しています。',
        reading: 'こしょをさがしています。',
        meaning_vi: 'Tôi đang tìm sách cổ.',
        meaning_en: 'I am looking for old books.',
      },
    ],
  },
  {
    kanji: '五',
    kun_reading: ['いつ.つ'],
    on_reading: ['ご'],
    han_viet: 'NGŨ',
    meaning_vi: 'năm',
    meaning_en: 'five',
    radicals: '二',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '五つのりんごがあります。',
        reading: 'いつつのりんごがあります。',
        meaning_vi: 'Có năm quả táo.',
        meaning_en: 'There are five apples.',
      },
      {
        sentence: '五千円を払いました。',
        reading: 'ごせんえんをはらいました。',
        meaning_vi: 'Tôi đã trả 5000 yên.',
        meaning_en: 'I paid 5000 yen.',
      },
    ],
  },
  {
    kanji: '後',
    kun_reading: ['あと', 'おく.れる', 'のち'],
    on_reading: ['ご', 'こう'],
    han_viet: 'HẬU',
    meaning_vi: 'sau, đằng sau, muộn',
    meaning_en: 'after, behind, late',
    radicals: '彳',
    strokes: 9,
    level: 'N5',
    examples: [
      {
        sentence: '授業の後で映画を見ます。',
        reading: 'じゅぎょうのあとでえいがをみます。',
        meaning_vi: 'Sau buổi học, tôi sẽ xem phim.',
        meaning_en: 'After class, I will watch a movie.',
      },
      {
        sentence: '彼は試験に後れました。',
        reading: 'かれはしけんにおくれました。',
        meaning_vi: 'Anh ấy đã trễ kỳ thi.',
        meaning_en: 'He was late for the exam.',
      },
    ],
  },
  {
    kanji: '午',
    kun_reading: [],
    on_reading: ['ご'],
    han_viet: 'NGỌ',
    meaning_vi: 'trưa, chiều',
    meaning_en: 'noon, afternoon',
    radicals: '干',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '午後に会いましょう。',
        reading: 'ごごにあいましょう。',
        meaning_vi: 'Hãy gặp vào buổi chiều.',
        meaning_en: "Let's meet in the afternoon.",
      },
      {
        sentence: '午前中は忙しいです。',
        reading: 'ごぜんちゅうはいそがしいです。',
        meaning_vi: 'Tôi bận cả buổi sáng.',
        meaning_en: "I'm busy in the morning.",
      },
    ],
  },
  {
    kanji: '語',
    kun_reading: ['かた.る', 'かた.らう'],
    on_reading: ['ご'],
    han_viet: 'NGỮ',
    meaning_vi: 'ngôn từ, nói/kể',
    meaning_en: 'language, talk',
    radicals: '言',
    strokes: 14,
    level: 'N5',
    examples: [
      {
        sentence: '日本語を勉強しています。',
        reading: 'にほんごをべんきょうしています。',
        meaning_vi: 'Tôi đang học tiếng Nhật.',
        meaning_en: 'I am studying Japanese.',
      },
      {
        sentence: '彼は物語を語った。',
        reading: 'かれはものがたりをかたった。',
        meaning_vi: 'Anh ấy đã kể một câu chuyện.',
        meaning_en: 'He told a story.',
      },
    ],
  },
  {
    kanji: '校',
    kun_reading: [],
    on_reading: ['こう'],
    han_viet: 'GIÁO',
    meaning_vi: 'trường học',
    meaning_en: 'school',
    radicals: '木',
    strokes: 10,
    level: 'N5',
    examples: [
      {
        sentence: '学校に行きます。',
        reading: 'がっこうにいきます。',
        meaning_vi: 'Tôi đi đến trường.',
        meaning_en: 'I go to school.',
      },
      {
        sentence: '高校の友達と会いました。',
        reading: 'こうこうのともだちとあいました。',
        meaning_vi: 'Tôi đã gặp bạn cấp ba.',
        meaning_en: 'I met my high school friend.',
      },
    ],
  },
  {
    kanji: '口',
    kun_reading: ['くち'],
    on_reading: ['こう', 'く'],
    han_viet: 'KHẨU',
    meaning_vi: 'miệng',
    meaning_en: 'mouth',
    radicals: '口',
    strokes: 3,
    level: 'N5',
    examples: [
      {
        sentence: '口を大きく開けてください。',
        reading: 'くちをおおきくあけてください。',
        meaning_vi: 'Hãy mở miệng to ra.',
        meaning_en: 'Please open your mouth wide.',
      },
      {
        sentence: '彼は甘口のカレーが好きです。',
        reading: 'かれはあまくちのカレーがすきです。',
        meaning_vi: 'Anh ấy thích cà ri vị ngọt.',
        meaning_en: 'He likes sweet curry.',
      },
    ],
  },
  {
    kanji: '行',
    kun_reading: ['い.く', 'ゆ.く', 'おこな.う'],
    on_reading: ['こう'],
    han_viet: 'HÀNH',
    meaning_vi: 'đi, tiến hành',
    meaning_en: 'go, conduct',
    radicals: '行',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: '私は学校へ行きます。',
        reading: 'わたしはがっこうへいきます。',
        meaning_vi: 'Tôi đi đến trường.',
        meaning_en: 'I go to school.',
      },
      {
        sentence: '旅行が大好きです。',
        reading: 'りょこうがだいすきです。',
        meaning_vi: 'Tôi rất thích đi du lịch.',
        meaning_en: 'I love traveling.',
      },
    ],
  },
  {
    kanji: '高',
    kun_reading: ['たか.い', 'たか.まる', 'たか.める'],
    on_reading: ['こう'],
    han_viet: 'CAO',
    meaning_vi: 'cao, nâng cao, đắt',
    meaning_en: 'high, tall, expensive',
    radicals: '高',
    strokes: 10,
    level: 'N5',
    examples: [
      {
        sentence: 'この建物はとても高いです。',
        reading: 'このたてものはとてもたかいです。',
        meaning_vi: 'Tòa nhà này rất cao.',
        meaning_en: 'This building is very tall.',
      },
      {
        sentence: 'この本は値段が高い。',
        reading: 'このほんはねだんがたかい。',
        meaning_vi: 'Cuốn sách này có giá cao.',
        meaning_en: 'This book is expensive.',
      },
    ],
  },
  {
    kanji: '国',
    kun_reading: ['くに'],
    on_reading: ['こく'],
    han_viet: 'QUỐC',
    meaning_vi: 'đất nước',
    meaning_en: 'country, nation',
    radicals: '囗',
    strokes: 8,
    level: 'N5',
    examples: [
      {
        sentence: '日本は美しい国です。',
        reading: 'にほんはうつくしいくにです。',
        meaning_vi: 'Nhật Bản là một đất nước đẹp.',
        meaning_en: 'Japan is a beautiful country.',
      },
      {
        sentence: '中国に行ったことがありますか？',
        reading: 'ちゅうごくにいったことがありますか？',
        meaning_vi: 'Bạn đã từng đến Trung Quốc chưa?',
        meaning_en: 'Have you ever been to China?',
      },
    ],
  },
  {
    kanji: '今',
    kun_reading: ['いま'],
    on_reading: ['こん', 'きん'],
    han_viet: 'KIM',
    meaning_vi: 'bây giờ, hiện tại',
    meaning_en: 'now, present',
    radicals: '人',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '今何時ですか？',
        reading: 'いまなんじですか？',
        meaning_vi: 'Bây giờ là mấy giờ?',
        meaning_en: 'What time is it now?',
      },
      {
        sentence: '今週の予定は何ですか？',
        reading: 'こんしゅうのよていはなんですか？',
        meaning_vi: 'Lịch trình tuần này là gì?',
        meaning_en: 'What is the schedule for this week?',
      },
    ],
  },
  {
    kanji: '左',
    kun_reading: ['ひだり'],
    on_reading: ['さ'],
    han_viet: 'TẢ',
    meaning_vi: 'bên trái',
    meaning_en: 'left',
    radicals: '工',
    strokes: 5,
    level: 'N5',
    examples: [
      {
        sentence: '左に曲がってください。',
        reading: 'ひだりにまがってください。',
        meaning_vi: 'Hãy rẽ trái.',
        meaning_en: 'Please turn left.',
      },
      {
        sentence: '左手で書く。',
        reading: 'ひだりてでかく。',
        meaning_vi: 'Viết bằng tay trái.',
        meaning_en: 'Write with the left hand.',
      },
    ],
  },
  {
    kanji: '三',
    kun_reading: ['みっつ'],
    on_reading: ['さん'],
    han_viet: 'TAM',
    meaning_vi: 'ba, số ba',
    meaning_en: 'three',
    radicals: '一',
    strokes: 3,
    level: 'N5',
    examples: [
      {
        sentence: 'リンゴを三つください。',
        reading: 'りんごをみっつください。',
        meaning_vi: 'Cho tôi ba quả táo.',
        meaning_en: 'Please give me three apples.',
      },
      {
        sentence: '私は三日間旅行しました。',
        reading: 'わたしはみっかかんりょこうしました。',
        meaning_vi: 'Tôi đã đi du lịch trong ba ngày.',
        meaning_en: 'I traveled for three days.',
      },
    ],
  },
  {
    kanji: '山',
    kun_reading: ['やま'],
    on_reading: ['さん'],
    han_viet: 'SAN',
    meaning_vi: 'núi',
    meaning_en: 'mountain',
    radicals: '山',
    strokes: 3,
    level: 'N5',
    examples: [
      {
        sentence: '富士山は日本で一番高い山です。',
        reading: 'ふじさんはにほんでいちばんたかいやまです。',
        meaning_vi: 'Núi Phú Sĩ là ngọn núi cao nhất ở Nhật.',
        meaning_en: 'Mount Fuji is the highest mountain in Japan.',
      },
      {
        sentence: '山に登るのが好きです。',
        reading: 'やまにのぼるのがすきです。',
        meaning_vi: 'Tôi thích leo núi.',
        meaning_en: 'I like climbing mountains.',
      },
    ],
  },
  {
    kanji: '四',
    kun_reading: ['よっつ', 'よん', 'よ'],
    on_reading: ['し'],
    han_viet: 'TỨ',
    meaning_vi: 'số bốn',
    meaning_en: 'four',
    radicals: '囗',
    strokes: 5,
    level: 'N5',
    examples: [
      {
        sentence: '四月は春の季節です。',
        reading: 'しがつははるのきせつです。',
        meaning_vi: 'Tháng tư là mùa xuân.',
        meaning_en: 'April is the spring season.',
      },
      {
        sentence: 'テーブルの上に四つのコップがあります。',
        reading: 'テーブルのうえによっつのコップがあります。',
        meaning_vi: 'Có bốn cái cốc trên bàn.',
        meaning_en: 'There are four cups on the table.',
      },
    ],
  },
  {
    kanji: '子',
    kun_reading: ['こ'],
    on_reading: ['し', 'す'],
    han_viet: 'TỬ',
    meaning_vi: 'trẻ con',
    meaning_en: 'child',
    radicals: '子',
    strokes: 3,
    level: 'N5',
    examples: [
      {
        sentence: '子供は公園で遊んでいます。',
        reading: 'こどもはこうえんであそんでいます。',
        meaning_vi: 'Đứa trẻ đang chơi ở công viên.',
        meaning_en: 'The child is playing in the park.',
      },
      {
        sentence: '王子は王様の息子です。',
        reading: 'おうじはおうさまのむすこです。',
        meaning_vi: 'Hoàng tử là con trai của nhà vua.',
        meaning_en: "The prince is the king's son.",
      },
    ],
  },
  {
    kanji: '耳',
    kun_reading: ['みみ'],
    on_reading: ['じ'],
    han_viet: 'NHĨ',
    meaning_vi: 'tai',
    meaning_en: 'ear',
    radicals: '耳',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: '彼は耳がいいです。',
        reading: 'かれはみみがいいです。',
        meaning_vi: 'Anh ấy có thính giác tốt.',
        meaning_en: 'He has good hearing.',
      },
      {
        sentence: '耳目を引くニュース。',
        reading: 'じもくをひくニュース。',
        meaning_vi: 'Tin tức thu hút sự chú ý.',
        meaning_en: 'News that catches the eye and ear.',
      },
    ],
  },
  {
    kanji: '時',
    kun_reading: ['とき'],
    on_reading: ['じ'],
    han_viet: 'THỜI, THÌ',
    meaning_vi: 'thời gian, giờ giấc',
    meaning_en: 'time, hour',
    radicals: '日',
    strokes: 10,
    level: 'N5',
    examples: [
      {
        sentence: '今は何時ですか？',
        reading: 'いまはなんじですか？',
        meaning_vi: 'Bây giờ là mấy giờ?',
        meaning_en: 'What time is it now?',
      },
      {
        sentence: '時計を持っていますか？',
        reading: 'とけいをもっていますか？',
        meaning_vi: 'Bạn có đồng hồ không?',
        meaning_en: 'Do you have a watch?',
      },
    ],
  },
  {
    kanji: '七',
    kun_reading: ['なな.つ', 'なな', 'なの'],
    on_reading: ['しち'],
    han_viet: 'THẤT',
    meaning_vi: 'số bảy',
    meaning_en: 'seven',
    radicals: '一',
    strokes: 2,
    level: 'N5',
    examples: [
      {
        sentence: '今日は七月七日です。',
        reading: 'きょうはしちがつなのかです。',
        meaning_vi: 'Hôm nay là ngày 7 tháng 7.',
        meaning_en: 'Today is July 7th.',
      },
      {
        sentence: '七つのボールがあります。',
        reading: 'ななつのボールがあります。',
        meaning_vi: 'Có bảy quả bóng.',
        meaning_en: 'There are seven balls.',
      },
    ],
  },
  {
    kanji: '車',
    kun_reading: ['くるま'],
    on_reading: ['しゃ'],
    han_viet: 'XA',
    meaning_vi: 'xe, ô tô',
    meaning_en: 'car, vehicle',
    radicals: '車',
    strokes: 7,
    level: 'N5',
    examples: [
      {
        sentence: 'これは私の車です。',
        reading: 'これはわたしのくるまです。',
        meaning_vi: 'Đây là xe của tôi.',
        meaning_en: 'This is my car.',
      },
      {
        sentence: '自転車に乗るのが好きです。',
        reading: 'じてんしゃにのるのがすきです。',
        meaning_vi: 'Tôi thích đi xe đạp.',
        meaning_en: 'I like riding bicycles.',
      },
    ],
  },
  {
    kanji: '社',
    kun_reading: ['やしろ'],
    on_reading: ['しゃ'],
    han_viet: 'XÃ',
    meaning_vi: 'đền, miếu, công ty',
    meaning_en: 'shrine, company',
    radicals: '示',
    strokes: 7,
    level: 'N5',
    examples: [
      {
        sentence: '私は会社で働いています。',
        reading: 'わたしはかいしゃではたらいています。',
        meaning_vi: 'Tôi làm việc tại công ty.',
        meaning_en: 'I work at a company.',
      },
      {
        sentence: '神社に行ったことがありますか？',
        reading: 'じんじゃにいったことがありますか？',
        meaning_vi: 'Bạn đã từng đến đền thờ Thần đạo chưa?',
        meaning_en: 'Have you ever been to a Shinto shrine?',
      },
    ],
  },
  {
    kanji: '手',
    kun_reading: ['て'],
    on_reading: ['しゅ'],
    han_viet: 'THỦ',
    meaning_vi: 'tay',
    meaning_en: 'hand',
    radicals: '手',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '彼は手を振った。',
        reading: 'かれはてをふった。',
        meaning_vi: 'Anh ấy vẫy tay.',
        meaning_en: 'He waved his hand.',
      },
      {
        sentence: '彼は空手を習っています。',
        reading: 'かれはからてをならっています。',
        meaning_vi: 'Anh ấy đang học karate.',
        meaning_en: 'He is learning karate.',
      },
    ],
  },
  {
    kanji: '手',
    kun_reading: ['て'],
    on_reading: ['しゅ'],
    han_viet: 'THỦ',
    meaning_vi: 'tay',
    meaning_en: 'hand',
    radicals: '手',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '彼は手を振った。',
        reading: 'かれはてをふった。',
        meaning_vi: 'Anh ấy vẫy tay.',
        meaning_en: 'He waved his hand.',
      },
      {
        sentence: '彼は空手を習っています。',
        reading: 'かれはからてをならっています。',
        meaning_vi: 'Anh ấy đang học karate.',
        meaning_en: 'He is learning karate.',
      },
    ],
  },
  {
    kanji: '十',
    kun_reading: ['とお', 'と'],
    on_reading: ['じゅう', 'じ'],
    han_viet: 'THẬP',
    meaning_vi: 'mười',
    meaning_en: 'ten',
    radicals: '十',
    strokes: 2,
    level: 'N5',
    examples: [
      {
        sentence: '彼は十歳です。',
        reading: 'かれはじゅっさいです。',
        meaning_vi: 'Anh ấy 10 tuổi.',
        meaning_en: 'He is ten years old.',
      },
      {
        sentence: '十日後に会いましょう。',
        reading: 'とおかごにあいましょう。',
        meaning_vi: 'Chúng ta gặp lại sau 10 ngày nhé.',
        meaning_en: "Let's meet again in ten days.",
      },
    ],
  },
  {
    kanji: '出',
    kun_reading: ['だ.す', 'で.る'],
    on_reading: ['しゅつ'],
    han_viet: 'XUẤT',
    meaning_vi: 'xuất, rời đi, ra đi',
    meaning_en: 'exit, leave',
    radicals: '凵',
    strokes: 5,
    level: 'N5',
    examples: [
      {
        sentence: '駅を出ます。',
        reading: 'えきをでます。',
        meaning_vi: 'Tôi rời khỏi nhà ga.',
        meaning_en: 'I am leaving the station.',
      },
      {
        sentence: '手紙を出しました。',
        reading: 'てがみをだしました。',
        meaning_vi: 'Tôi đã gửi thư.',
        meaning_en: 'I sent a letter.',
      },
    ],
  },
  {
    kanji: '書',
    kun_reading: ['か.く'],
    on_reading: ['しょ'],
    han_viet: 'THƯ',
    meaning_vi: 'viết',
    meaning_en: 'write',
    radicals: '曰',
    strokes: 10,
    level: 'N5',
    examples: [
      {
        sentence: '私は手紙を書きました。',
        reading: 'わたしはてがみをかきました。',
        meaning_vi: 'Tôi đã viết thư.',
        meaning_en: 'I wrote a letter.',
      },
      {
        sentence: 'この辞書は便利です。',
        reading: 'このじしょはべんりです。',
        meaning_vi: 'Cuốn từ điển này rất tiện lợi.',
        meaning_en: 'This dictionary is convenient.',
      },
    ],
  },
  {
    kanji: '女',
    kun_reading: ['おんな', 'め'],
    on_reading: ['じょ', 'にょう'],
    han_viet: 'NỮ',
    meaning_vi: 'phụ nữ',
    meaning_en: 'woman',
    radicals: '女',
    strokes: 3,
    level: 'N5',
    examples: [
      {
        sentence: '彼女は優しい人です。',
        reading: 'かのじょはやさしいひとです。',
        meaning_vi: 'Cô ấy là một người tốt bụng.',
        meaning_en: 'She is a kind person.',
      },
      {
        sentence: 'その女の子はかわいい。',
        reading: 'そのおんなのこはかわいい。',
        meaning_vi: 'Bé gái đó rất dễ thương.',
        meaning_en: 'That girl is cute.',
      },
    ],
  },
  {
    kanji: '女',
    kun_reading: ['おんな', 'め'],
    on_reading: ['じょ', 'にょう'],
    han_viet: 'NỮ',
    meaning_vi: 'phụ nữ',
    meaning_en: 'woman',
    radicals: '女',
    strokes: 3,
    level: 'N5',
    examples: [
      {
        sentence: '彼女は優しい人です。',
        reading: 'かのじょはやさしいひとです。',
        meaning_vi: 'Cô ấy là một người tốt bụng.',
        meaning_en: 'She is a kind person.',
      },
      {
        sentence: 'その女の子はかわいい。',
        reading: 'そのおんなのこはかわいい。',
        meaning_vi: 'Bé gái đó rất dễ thương.',
        meaning_en: 'That girl is cute.',
      },
    ],
  },
  {
    kanji: '少',
    kun_reading: ['すこ.し', 'すく.ない'],
    on_reading: ['しょう'],
    han_viet: 'THIỂU',
    meaning_vi: 'một chút, một ít',
    meaning_en: 'few, little',
    radicals: '小',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '少し待ってください。',
        reading: 'すこしまってください。',
        meaning_vi: 'Vui lòng chờ một chút.',
        meaning_en: 'Please wait a little.',
      },
      {
        sentence: '彼の友達は少ないです。',
        reading: 'かれのともだちはすくないです。',
        meaning_vi: 'Anh ấy có ít bạn.',
        meaning_en: 'He has few friends.',
      },
    ],
  },
  {
    kanji: '上',
    kun_reading: ['うえ', 'かみ', 'あ.げる', 'あ.がる'],
    on_reading: ['しょう', 'じょう'],
    han_viet: 'THƯỢNG',
    meaning_vi: 'trên, phía trên',
    meaning_en: 'up, above',
    radicals: '一',
    strokes: 3,
    level: 'N5',
    examples: [
      {
        sentence: '本は机の上にあります。',
        reading: 'ほんはつくえのうえにあります。',
        meaning_vi: 'Cuốn sách nằm trên bàn.',
        meaning_en: 'The book is on the desk.',
      },
      {
        sentence: '彼は上手に話せます。',
        reading: 'かれはじょうずにはなせます。',
        meaning_vi: 'Anh ấy nói rất giỏi.',
        meaning_en: 'He can speak well.',
      },
    ],
  },
  {
    kanji: '食',
    kun_reading: ['た.べる', 'く.らう'],
    on_reading: ['しょく'],
    han_viet: 'THỰC',
    meaning_vi: 'ăn',
    meaning_en: 'eat',
    radicals: '食',
    strokes: 9,
    level: 'N5',
    examples: [
      {
        sentence: '毎日ご飯を食べます。',
        reading: 'まいにちごはんをたべます。',
        meaning_vi: 'Tôi ăn cơm mỗi ngày.',
        meaning_en: 'I eat rice every day.',
      },
      {
        sentence: '彼は食堂で昼ご飯を食べました。',
        reading: 'かれはしょくどうでひるごはんをたべました。',
        meaning_vi: 'Anh ấy đã ăn trưa ở nhà ăn.',
        meaning_en: 'He had lunch at the cafeteria.',
      },
    ],
  },
  {
    kanji: '新',
    kun_reading: ['あたら.しい', 'あら.た', 'にい'],
    on_reading: ['しん'],
    han_viet: 'TÂN',
    meaning_vi: 'mới',
    meaning_en: 'new',
    radicals: '斤',
    strokes: 13,
    level: 'N5',
    examples: [
      {
        sentence: '私は新しい本を買いました。',
        reading: 'わたしはあたらしいほんをかいました。',
        meaning_vi: 'Tôi đã mua một cuốn sách mới.',
        meaning_en: 'I bought a new book.',
      },
      {
        sentence: 'この新聞を読んでください。',
        reading: 'このしんぶんをよんでください。',
        meaning_vi: 'Hãy đọc tờ báo này.',
        meaning_en: 'Please read this newspaper.',
      },
    ],
  },
  {
    kanji: '人',
    kun_reading: ['ひと'],
    on_reading: ['じん', 'にん'],
    han_viet: 'NHÂN',
    meaning_vi: 'người',
    meaning_en: 'person',
    radicals: '人',
    strokes: 2,
    level: 'N5',
    examples: [
      {
        sentence: 'この部屋に何人いますか？',
        reading: 'このへやになんにんいますか？',
        meaning_vi: 'Có bao nhiêu người trong phòng này?',
        meaning_en: 'How many people are in this room?',
      },
      {
        sentence: '彼はとてもいい人です。',
        reading: 'かれはとてもいいひとです。',
        meaning_vi: 'Anh ấy là một người rất tốt.',
        meaning_en: 'He is a very nice person.',
      },
    ],
  },
  {
    kanji: '水',
    kun_reading: ['みず'],
    on_reading: ['すい'],
    han_viet: 'THỦY',
    meaning_vi: 'nước',
    meaning_en: 'water',
    radicals: '水',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '水を飲みます。',
        reading: 'みずをのみます。',
        meaning_vi: 'Tôi uống nước.',
        meaning_en: 'I drink water.',
      },
      {
        sentence: '水泳は楽しいスポーツです。',
        reading: 'すいえいはたのしいスポーツです。',
        meaning_vi: 'Bơi lội là một môn thể thao thú vị.',
        meaning_en: 'Swimming is a fun sport.',
      },
    ],
  },
  {
    kanji: '生',
    kun_reading: ['い.きる', 'う.む', 'は.やす', 'なま', 'き'],
    on_reading: ['せい', 'しょう'],
    han_viet: 'SINH',
    meaning_vi: 'sống, sinh ra',
    meaning_en: 'life, birth',
    radicals: '生',
    strokes: 5,
    level: 'N5',
    examples: [
      {
        sentence: '彼は日本で生まれました。',
        reading: 'かれはにほんでうまれました。',
        meaning_vi: 'Anh ấy sinh ra ở Nhật Bản.',
        meaning_en: 'He was born in Japan.',
      },
      {
        sentence: '私は学生です。',
        reading: 'わたしはがくせいです。',
        meaning_vi: 'Tôi là học sinh.',
        meaning_en: 'I am a student.',
      },
    ],
  },
  {
    kanji: '西',
    kun_reading: ['にし'],
    on_reading: ['せい', 'さい'],
    han_viet: 'TÂY',
    meaning_vi: 'phía tây',
    meaning_en: 'west',
    radicals: '西',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: '太陽は西に沈みます。',
        reading: 'たいようはにしにしずみます。',
        meaning_vi: 'Mặt trời lặn ở phía tây.',
        meaning_en: 'The sun sets in the west.',
      },
      {
        sentence: '彼は西の方から来ました。',
        reading: 'かれはにしのほうからきました。',
        meaning_vi: 'Anh ấy đến từ phía tây.',
        meaning_en: 'He came from the west.',
      },
    ],
  },
  {
    kanji: '川',
    kun_reading: ['かわ'],
    on_reading: ['せん'],
    han_viet: 'XUYÊN',
    meaning_vi: 'sông',
    meaning_en: 'river',
    radicals: '川',
    strokes: 3,
    level: 'N5',
    examples: [
      {
        sentence: '川で泳ぎます。',
        reading: 'かわでおよぎます。',
        meaning_vi: 'Tôi bơi ở sông.',
        meaning_en: 'I swim in the river.',
      },
      {
        sentence: '川口はとても美しいです。',
        reading: 'かわぐちはとてもうつくしいです。',
        meaning_vi: 'Cửa sông rất đẹp.',
        meaning_en: 'The river mouth is very beautiful.',
      },
    ],
  },
  {
    kanji: '千',
    kun_reading: ['ち'],
    on_reading: ['せん'],
    han_viet: 'THIÊN',
    meaning_vi: 'một ngàn',
    meaning_en: 'thousand',
    radicals: '千',
    strokes: 3,
    level: 'N5',
    examples: [
      {
        sentence: '私は千円持っています。',
        reading: 'わたしはせんえんもっています。',
        meaning_vi: 'Tôi có 1000 yên.',
        meaning_en: 'I have 1000 yen.',
      },
      {
        sentence: '千鳥は鳥の種類の一つです。',
        reading: 'ちどりはとりのしゅるいのひとつです。',
        meaning_vi: 'Chidori là một loại chim.',
        meaning_en: 'Chidori is a type of bird.',
      },
    ],
  },
  {
    kanji: '先',
    kun_reading: ['さき'],
    on_reading: ['せん'],
    han_viet: 'TIÊN',
    meaning_vi: 'phía trước, trước, tương lai',
    meaning_en: 'ahead, before, future',
    radicals: '先',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: '先生はとても親切です。',
        reading: 'せんせいはとてもしんせつです。',
        meaning_vi: 'Giáo viên rất tốt bụng.',
        meaning_en: 'The teacher is very kind.',
      },
      {
        sentence: '私は先週東京へ行きました。',
        reading: 'わたしはせんしゅうとうきょうへいきました。',
        meaning_vi: 'Tôi đã đi Tokyo vào tuần trước.',
        meaning_en: 'I went to Tokyo last week.',
      },
    ],
  },
  {
    kanji: '先',
    kun_reading: ['さき'],
    on_reading: ['せん'],
    han_viet: 'TIÊN',
    meaning_vi: 'phía trước, trước, tương lai',
    meaning_en: 'ahead, before, future',
    radicals: '先',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: '先生はとても親切です。',
        reading: 'せんせいはとてもしんせつです。',
        meaning_vi: 'Giáo viên rất tốt bụng.',
        meaning_en: 'The teacher is very kind.',
      },
      {
        sentence: '私は先週東京へ行きました。',
        reading: 'わたしはせんしゅうとうきょうへいきました。',
        meaning_vi: 'Tôi đã đi Tokyo vào tuần trước.',
        meaning_en: 'I went to Tokyo last week.',
      },
    ],
  },
  {
    kanji: '足',
    kun_reading: ['あし', 'た.りる', 'た.す'],
    on_reading: ['そく'],
    han_viet: 'TÚC',
    meaning_vi: 'chân, đầy đủ, thêm vào',
    meaning_en: 'foot, enough, add',
    radicals: '足',
    strokes: 7,
    level: 'N5',
    examples: [
      {
        sentence: '彼の足は長いです。',
        reading: 'かれのあしはながいです。',
        meaning_vi: 'Chân của anh ấy dài.',
        meaning_en: 'His legs are long.',
      },
      {
        sentence: 'お金が足りません。',
        reading: 'おかねがたりません。',
        meaning_vi: 'Không đủ tiền.',
        meaning_en: 'Not enough money.',
      },
    ],
  },
  {
    kanji: '多',
    kun_reading: ['おお.い'],
    on_reading: ['た'],
    han_viet: 'ĐA',
    meaning_vi: 'nhiều',
    meaning_en: 'many, much',
    radicals: '夕',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: '東京には人が多いです。',
        reading: 'とうきょうにはひとがおおいです。',
        meaning_vi: 'Ở Tokyo có nhiều người.',
        meaning_en: 'There are many people in Tokyo.',
      },
      {
        sentence: '質問が多すぎます。',
        reading: 'しつもんがおおすぎます。',
        meaning_vi: 'Có quá nhiều câu hỏi.',
        meaning_en: 'There are too many questions.',
      },
    ],
  },
  {
    kanji: '大',
    kun_reading: ['おお.きい'],
    on_reading: ['だい', 'たい'],
    han_viet: 'ĐẠI',
    meaning_vi: 'to, lớn',
    meaning_en: 'big, large',
    radicals: '大',
    strokes: 3,
    level: 'N5',
    examples: [
      {
        sentence: '大きい家に住んでいます。',
        reading: 'おおきいいえにすんでいます。',
        meaning_vi: 'Tôi sống trong một ngôi nhà lớn.',
        meaning_en: 'I live in a big house.',
      },
      {
        sentence: '大学で勉強します。',
        reading: 'だいがくでべんきょうします。',
        meaning_vi: 'Tôi học ở đại học.',
        meaning_en: 'I study at a university.',
      },
    ],
  },
  {
    kanji: '男',
    kun_reading: ['おとこ'],
    on_reading: ['だん', 'なん'],
    han_viet: 'NAM',
    meaning_vi: 'đàn ông',
    meaning_en: 'man',
    radicals: '田',
    strokes: 7,
    level: 'N5',
    examples: [
      {
        sentence: '彼は優しい男の人です。',
        reading: 'かれはやさしいおとこのひとです。',
        meaning_vi: 'Anh ấy là một người đàn ông hiền lành.',
        meaning_en: 'He is a kind man.',
      },
      {
        sentence: '男の子が遊んでいます。',
        reading: 'おとこのこがあそんでいます。',
        meaning_vi: 'Một cậu bé đang chơi.',
        meaning_en: 'A boy is playing.',
      },
    ],
  },
  {
    kanji: '中',
    kun_reading: ['なか'],
    on_reading: ['ちゅう'],
    han_viet: 'TRUNG',
    meaning_vi: 'trong, bên trong',
    meaning_en: 'inside, middle',
    radicals: '丨',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '部屋の中に猫がいます。',
        reading: 'へやのなかにねこがいます。',
        meaning_vi: 'Có một con mèo trong phòng.',
        meaning_en: 'There is a cat in the room.',
      },
      {
        sentence: '中国に行きたいです。',
        reading: 'ちゅうごくにいきたいです。',
        meaning_vi: 'Tôi muốn đi Trung Quốc.',
        meaning_en: 'I want to go to China.',
      },
    ],
  },
  {
    kanji: '長',
    kun_reading: ['なが.い'],
    on_reading: ['ちょう'],
    han_viet: 'TRƯỜNG',
    meaning_vi: 'dài, trưởng',
    meaning_en: 'long, leader',
    radicals: '長',
    strokes: 8,
    level: 'N5',
    examples: [
      {
        sentence: '彼の髪はとても長いです。',
        reading: 'かれのかみはとてもながいです。',
        meaning_vi: 'Tóc của anh ấy rất dài.',
        meaning_en: 'His hair is very long.',
      },
      {
        sentence: '部長と話しました。',
        reading: 'ぶちょうとはなしました。',
        meaning_vi: 'Tôi đã nói chuyện với trưởng phòng.',
        meaning_en: 'I talked to the department head.',
      },
    ],
  },
  {
    kanji: '天',
    kun_reading: ['あめ', 'あま'],
    on_reading: ['てん'],
    han_viet: 'THIÊN',
    meaning_vi: 'trời, thiên',
    meaning_en: 'sky, heaven',
    radicals: '天',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '天気がいいですね。',
        reading: 'てんきがいいですね。',
        meaning_vi: 'Thời tiết đẹp nhỉ.',
        meaning_en: "The weather is nice, isn't it?",
      },
      {
        sentence: '彼は天使のように優しいです。',
        reading: 'かれはてんしのようにやさしいです。',
        meaning_vi: 'Anh ấy hiền như thiên thần vậy.',
        meaning_en: 'He is as kind as an angel.',
      },
    ],
  },
  {
    kanji: '店',
    kun_reading: ['みせ'],
    on_reading: ['てん'],
    han_viet: 'ĐIẾM',
    meaning_vi: 'cửa hàng',
    meaning_en: 'shop, store',
    radicals: '广',
    strokes: 8,
    level: 'N5',
    examples: [
      {
        sentence: 'この店はとても人気があります。',
        reading: 'このみせはとてもにんきがあります。',
        meaning_vi: 'Cửa hàng này rất nổi tiếng.',
        meaning_en: 'This store is very popular.',
      },
      {
        sentence: '店員に聞いてみましょう。',
        reading: 'てんいんにきいてみましょう。',
        meaning_vi: 'Hãy hỏi nhân viên cửa hàng xem.',
        meaning_en: "Let's ask the store clerk.",
      },
    ],
  },
  {
    kanji: '店',
    kun_reading: ['みせ'],
    on_reading: ['てん'],
    han_viet: 'ĐIẾM',
    meaning_vi: 'cửa hàng',
    meaning_en: 'shop, store',
    radicals: '广',
    strokes: 8,
    level: 'N5',
    examples: [
      {
        sentence: 'この店はとても人気があります。',
        reading: 'このみせはとてもにんきがあります。',
        meaning_vi: 'Cửa hàng này rất nổi tiếng.',
        meaning_en: 'This store is very popular.',
      },
      {
        sentence: '店員に聞いてみましょう。',
        reading: 'てんいんにきいてみましょう。',
        meaning_vi: 'Hãy hỏi nhân viên cửa hàng xem.',
        meaning_en: "Let's ask the store clerk.",
      },
    ],
  },
  {
    kanji: '土',
    kun_reading: ['つち'],
    on_reading: ['ど', 'と'],
    han_viet: 'THỔ',
    meaning_vi: 'đất',
    meaning_en: 'earth, soil',
    radicals: '土',
    strokes: 3,
    level: 'N5',
    examples: [
      {
        sentence: '土曜日に友達と遊びます。',
        reading: 'どようびにともだちとあそびます。',
        meaning_vi: 'Tôi sẽ đi chơi với bạn vào thứ bảy.',
        meaning_en: 'I will hang out with my friends on Saturday.',
      },
      {
        sentence: 'この土はとても肥えています。',
        reading: 'このつちはとてもこえています。',
        meaning_vi: 'Đất này rất màu mỡ.',
        meaning_en: 'This soil is very fertile.',
      },
    ],
  },
  {
    kanji: '東',
    kun_reading: ['ひがし'],
    on_reading: ['とう'],
    han_viet: 'ĐÔNG',
    meaning_vi: 'phía đông',
    meaning_en: 'east',
    radicals: '木',
    strokes: 8,
    level: 'N5',
    examples: [
      {
        sentence: '東京は日本の首都です。',
        reading: 'とうきょうはにほんのしゅとです。',
        meaning_vi: 'Tokyo là thủ đô của Nhật Bản.',
        meaning_en: 'Tokyo is the capital of Japan.',
      },
      {
        sentence: '東の空が明るくなってきた。',
        reading: 'ひがしのそらがあかるくなってきた。',
        meaning_vi: 'Bầu trời phía đông bắt đầu sáng lên.',
        meaning_en: 'The eastern sky is getting brighter.',
      },
    ],
  },
  {
    kanji: '道',
    kun_reading: ['みち'],
    on_reading: ['どう'],
    han_viet: 'ĐẠO',
    meaning_vi: 'đường, con đường',
    meaning_en: 'road, path',
    radicals: '辶',
    strokes: 12,
    level: 'N5',
    examples: [
      {
        sentence: 'この道をまっすぐ行ってください。',
        reading: 'このみちをまっすぐいってください。',
        meaning_vi: 'Hãy đi thẳng đường này.',
        meaning_en: 'Please go straight on this road.',
      },
      {
        sentence: '茶道を学びたいです。',
        reading: 'ちゃどうをまなびたいです。',
        meaning_vi: 'Tôi muốn học trà đạo.',
        meaning_en: 'I want to learn tea ceremony.',
      },
    ],
  },
  {
    kanji: '道',
    kun_reading: ['みち'],
    on_reading: ['どう'],
    han_viet: 'ĐẠO',
    meaning_vi: 'đường, con đường',
    meaning_en: 'road, path',
    radicals: '辶',
    strokes: 12,
    level: 'N5',
    examples: [
      {
        sentence: 'この道をまっすぐ行ってください。',
        reading: 'このみちをまっすぐいってください。',
        meaning_vi: 'Hãy đi thẳng đường này.',
        meaning_en: 'Please go straight on this road.',
      },
      {
        sentence: '茶道を学びたいです。',
        reading: 'ちゃどうをまなびたいです。',
        meaning_vi: 'Tôi muốn học trà đạo.',
        meaning_en: 'I want to learn tea ceremony.',
      },
    ],
  },
  {
    kanji: '南',
    kun_reading: ['みなみ'],
    on_reading: ['なん'],
    han_viet: 'NAM',
    meaning_vi: 'phía nam',
    meaning_en: 'south',
    radicals: '十',
    strokes: 9,
    level: 'N5',
    examples: [
      {
        sentence: '南の方が暖かいです。',
        reading: 'みなみのほうがあたたかいです。',
        meaning_vi: 'Phía nam ấm hơn.',
        meaning_en: 'The south is warmer.',
      },
      {
        sentence: '南北に長い国です。',
        reading: 'なんぼくにながいくにです。',
        meaning_vi: 'Đây là một đất nước kéo dài từ bắc xuống nam.',
        meaning_en: 'This is a long country from north to south.',
      },
    ],
  },
  {
    kanji: '二',
    kun_reading: ['ふた.つ'],
    on_reading: ['に'],
    han_viet: 'NHỊ',
    meaning_vi: 'hai, số hai',
    meaning_en: 'two',
    radicals: '二',
    strokes: 2,
    level: 'N5',
    examples: [
      {
        sentence: 'リンゴを二つ買いました。',
        reading: 'りんごをふたつかいました。',
        meaning_vi: 'Tôi đã mua hai quả táo.',
        meaning_en: 'I bought two apples.',
      },
      {
        sentence: '二人で映画を見ました。',
        reading: 'ふたりでえいがをみました。',
        meaning_vi: 'Hai người chúng tôi đã xem phim.',
        meaning_en: 'We watched a movie together.',
      },
    ],
  },
  {
    kanji: '日',
    kun_reading: ['ひ', 'か'],
    on_reading: ['にち', 'じつ'],
    han_viet: 'NHẬT',
    meaning_vi: 'ngày, mặt trời',
    meaning_en: 'day, sun',
    radicals: '日',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '今日はとても暑いです。',
        reading: 'きょうはとてもあついです。',
        meaning_vi: 'Hôm nay rất nóng.',
        meaning_en: 'Today is very hot.',
      },
      {
        sentence: '母の日にプレゼントをあげました。',
        reading: 'ははのひにぷれぜんとをあげました。',
        meaning_vi: 'Tôi đã tặng quà vào Ngày của Mẹ.',
        meaning_en: "I gave a gift on Mother's Day.",
      },
    ],
  },
  {
    kanji: '入',
    kun_reading: ['はい.る', 'い.れる'],
    on_reading: ['にゅう'],
    han_viet: 'NHẬP',
    meaning_vi: 'vào, điền vào',
    meaning_en: 'enter, insert',
    radicals: '入',
    strokes: 2,
    level: 'N5',
    examples: [
      {
        sentence: '部屋に入ってください。',
        reading: 'へやにはいってください。',
        meaning_vi: 'Hãy vào phòng.',
        meaning_en: 'Please enter the room.',
      },
      {
        sentence: '新しい学校に入学しました。',
        reading: 'あたらしいがっこうににゅうがくしました。',
        meaning_vi: 'Tôi đã nhập học vào trường mới.',
        meaning_en: 'I enrolled in a new school.',
      },
    ],
  },
  {
    kanji: '年',
    kun_reading: ['とし'],
    on_reading: ['ねん'],
    han_viet: 'NIÊN',
    meaning_vi: 'năm',
    meaning_en: 'year',
    radicals: '干',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: '今年は日本に行きます。',
        reading: 'ことしはにほんにいきます。',
        meaning_vi: 'Năm nay tôi sẽ đi Nhật Bản.',
        meaning_en: 'This year, I will go to Japan.',
      },
      {
        sentence: '去年の夏はとても暑かったです。',
        reading: 'きょねんのなつはとてもあつかったです。',
        meaning_vi: 'Mùa hè năm ngoái rất nóng.',
        meaning_en: 'Last summer was very hot.',
      },
    ],
  },
  {
    kanji: '買',
    kun_reading: ['か.う'],
    on_reading: ['ばい'],
    han_viet: 'MÃI',
    meaning_vi: 'mua',
    meaning_en: 'buy',
    radicals: '貝',
    strokes: 12,
    level: 'N5',
    examples: [
      {
        sentence: '新しい靴を買いました。',
        reading: 'あたらしいくつをかいました。',
        meaning_vi: 'Tôi đã mua một đôi giày mới.',
        meaning_en: 'I bought new shoes.',
      },
      {
        sentence: '毎日スーパーで買い物をします。',
        reading: 'まいにちすーぱーでかいものをします。',
        meaning_vi: 'Tôi đi mua sắm ở siêu thị mỗi ngày.',
        meaning_en: 'I shop at the supermarket every day.',
      },
    ],
  },
  {
    kanji: '白',
    kun_reading: ['しろ.い', 'しろ'],
    on_reading: ['はく', 'びゃく'],
    han_viet: 'BẠCH',
    meaning_vi: 'trắng',
    meaning_en: 'white',
    radicals: '白',
    strokes: 5,
    level: 'N5',
    examples: [
      {
        sentence: '白い犬が好きです。',
        reading: 'しろいいぬがすきです。',
        meaning_vi: 'Tôi thích chó màu trắng.',
        meaning_en: 'I like white dogs.',
      },
      {
        sentence: '彼のシャツは白いです。',
        reading: 'かれのしゃつはしろいです。',
        meaning_vi: 'Áo sơ mi của anh ấy màu trắng.',
        meaning_en: 'His shirt is white.',
      },
    ],
  },
  {
    kanji: '白',
    kun_reading: ['しろ.い', 'しろ'],
    on_reading: ['はく', 'びゃく'],
    han_viet: 'BẠCH',
    meaning_vi: 'trắng',
    meaning_en: 'white',
    radicals: '白',
    strokes: 5,
    level: 'N5',
    examples: [
      {
        sentence: '白い犬が好きです。',
        reading: 'しろいいぬがすきです。',
        meaning_vi: 'Tôi thích chó màu trắng.',
        meaning_en: 'I like white dogs.',
      },
      {
        sentence: '彼のシャツは白いです。',
        reading: 'かれのしゃつはしろいです。',
        meaning_vi: 'Áo sơ mi của anh ấy màu trắng.',
        meaning_en: 'His shirt is white.',
      },
    ],
  },
  {
    kanji: '八',
    kun_reading: ['やっ.つ', 'や.つ', 'よう'],
    on_reading: ['はち'],
    han_viet: 'BÁT',
    meaning_vi: 'tám, số tám',
    meaning_en: 'eight',
    radicals: '八',
    strokes: 2,
    level: 'N5',
    examples: [
      {
        sentence: '八つのリンゴがあります。',
        reading: 'やっつのりんごがあります。',
        meaning_vi: 'Có tám quả táo.',
        meaning_en: 'There are eight apples.',
      },
      {
        sentence: '八百円を払いました。',
        reading: 'はっぴゃくえんをはらいました。',
        meaning_vi: 'Tôi đã trả 800 yên.',
        meaning_en: 'I paid 800 yen.',
      },
    ],
  },
  {
    kanji: '百',
    kun_reading: [],
    on_reading: ['ひゃく'],
    han_viet: 'BÁCH',
    meaning_vi: 'một trăm',
    meaning_en: 'hundred',
    radicals: '白',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: '百円を貸してください。',
        reading: 'ひゃくえんをかしてください。',
        meaning_vi: 'Hãy cho tôi mượn 100 yên.',
        meaning_en: 'Please lend me 100 yen.',
      },
    ],
  },
  {
    kanji: '父',
    kun_reading: ['ちち'],
    on_reading: ['ふ'],
    han_viet: 'PHỤ',
    meaning_vi: 'bố',
    meaning_en: 'father',
    radicals: '父',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '私の父は先生です。',
        reading: 'わたしのちちはせんせいです。',
        meaning_vi: 'Bố tôi là giáo viên.',
        meaning_en: 'My father is a teacher.',
      },
      {
        sentence: '祖父は日本に住んでいます。',
        reading: 'そふはにほんにすんでいます。',
        meaning_vi: 'Ông tôi sống ở Nhật Bản.',
        meaning_en: 'My grandfather lives in Japan.',
      },
    ],
  },
  {
    kanji: '分',
    kun_reading: ['わ.ける', 'わ.かれる', 'わか.る'],
    on_reading: ['ぶん', 'ぶ', 'ふん'],
    han_viet: 'PHÂN',
    meaning_vi: 'phần, phút, phân chia, hiểu',
    meaning_en: 'part, minute, divide, understand',
    radicals: '刀',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: 'この問題が分かりますか？',
        reading: 'このもんだいがわかりますか？',
        meaning_vi: 'Bạn có hiểu bài toán này không?',
        meaning_en: 'Do you understand this problem?',
      },
      {
        sentence: '十分休憩しましょう。',
        reading: 'じゅっぷんきゅうけいしましょう。',
        meaning_vi: 'Hãy nghỉ 10 phút.',
        meaning_en: "Let's take a 10-minute break.",
      },
    ],
  },
  {
    kanji: '聞',
    kun_reading: ['き.く', 'き.こえる'],
    on_reading: ['ぶん', 'もん'],
    han_viet: 'VĂN',
    meaning_vi: 'nghe, hỏi',
    meaning_en: 'hear, listen, ask',
    radicals: '耳',
    strokes: 14,
    level: 'N5',
    examples: [
      {
        sentence: '新聞を毎日読みます。',
        reading: 'しんぶんをまいにちよみます。',
        meaning_vi: 'Tôi đọc báo mỗi ngày.',
        meaning_en: 'I read the newspaper every day.',
      },
      {
        sentence: '音楽を聞くのが好きです。',
        reading: 'おんがくをきくのがすきです。',
        meaning_vi: 'Tôi thích nghe nhạc.',
        meaning_en: 'I like listening to music.',
      },
    ],
  },
  {
    kanji: '聞',
    kun_reading: ['き.く', 'き.こえる'],
    on_reading: ['ぶん', 'もん'],
    han_viet: 'VĂN',
    meaning_vi: 'nghe, hỏi',
    meaning_en: 'hear, listen, ask',
    radicals: '耳',
    strokes: 14,
    level: 'N5',
    examples: [
      {
        sentence: '新聞を毎日読みます。',
        reading: 'しんぶんをまいにちよみます。',
        meaning_vi: 'Tôi đọc báo mỗi ngày.',
        meaning_en: 'I read the newspaper every day.',
      },
      {
        sentence: '音楽を聞くのが好きです。',
        reading: 'おんがくをきくのがすきです。',
        meaning_vi: 'Tôi thích nghe nhạc.',
        meaning_en: 'I like listening to music.',
      },
    ],
  },
  {
    kanji: '母',
    kun_reading: ['はは'],
    on_reading: ['ぼ'],
    han_viet: 'MẪU',
    meaning_vi: 'mẹ',
    meaning_en: 'mother',
    radicals: '母',
    strokes: 5,
    level: 'N5',
    examples: [
      {
        sentence: '母の日にプレゼントをあげました。',
        reading: 'ははのひにぷれぜんとをあげました。',
        meaning_vi: 'Tôi đã tặng quà vào Ngày của Mẹ.',
        meaning_en: "I gave a gift on Mother's Day.",
      },
      {
        sentence: '祖母は料理が得意です。',
        reading: 'そぼはりょうりがとくいです。',
        meaning_vi: 'Bà tôi rất giỏi nấu ăn.',
        meaning_en: 'My grandmother is good at cooking.',
      },
    ],
  },
  {
    kanji: '北',
    kun_reading: ['きた'],
    on_reading: ['ほく'],
    han_viet: 'BẮC',
    meaning_vi: 'phía bắc',
    meaning_en: 'north',
    radicals: '匕',
    strokes: 5,
    level: 'N5',
    examples: [
      {
        sentence: '日本の北には北海道があります。',
        reading: 'にほんのきたにはほっかいどうがあります。',
        meaning_vi: 'Phía bắc Nhật Bản có Hokkaido.',
        meaning_en: 'In the north of Japan, there is Hokkaido.',
      },
    ],
  },
  {
    kanji: '木',
    kun_reading: ['き', 'こ'],
    on_reading: ['ぼく', 'もく'],
    han_viet: 'MỘC',
    meaning_vi: 'cây, rừng',
    meaning_en: 'tree, wood',
    radicals: '木',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '庭に大きな木があります。',
        reading: 'にわにおおきなきがあります。',
        meaning_vi: 'Có một cái cây lớn trong vườn.',
        meaning_en: 'There is a big tree in the garden.',
      },
    ],
  },
  {
    kanji: '毎',
    kun_reading: [],
    on_reading: ['まい'],
    han_viet: 'MỖI',
    meaning_vi: 'mỗi, hàng',
    meaning_en: 'every',
    radicals: '毋',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: '毎日、日本語を勉強しています。',
        reading: 'まいにち、にほんごをべんきょうしています。',
        meaning_vi: 'Tôi học tiếng Nhật mỗi ngày.',
        meaning_en: 'I study Japanese every day.',
      },
    ],
  },
  {
    kanji: '万',
    kun_reading: [],
    on_reading: ['まん', 'ばん'],
    han_viet: 'VẠN',
    meaning_vi: 'vạn, mười ngàn',
    meaning_en: 'ten thousand',
    radicals: '一',
    strokes: 3,
    level: 'N5',
    examples: [
      {
        sentence: '一万円を持っています。',
        reading: 'いちまんえんをもっています。',
        meaning_vi: 'Tôi có 10.000 yên.',
        meaning_en: 'I have 10,000 yen.',
      },
    ],
  },
  {
    kanji: '名',
    kun_reading: ['な'],
    on_reading: ['めい', 'みょう'],
    han_viet: 'DANH',
    meaning_vi: 'danh, tên',
    meaning_en: 'name, reputation',
    radicals: '口',
    strokes: 6,
    level: 'N5',
    examples: [
      {
        sentence: 'あなたの名前は何ですか？',
        reading: 'あなたのなまえはなんですか？',
        meaning_vi: 'Tên bạn là gì?',
        meaning_en: 'What is your name?',
      },
      {
        sentence: '彼は有名な歌手です。',
        reading: 'かれはゆうめいなかしゅです。',
        meaning_vi: 'Anh ấy là một ca sĩ nổi tiếng.',
        meaning_en: 'He is a famous singer.',
      },
    ],
  },
  {
    kanji: '目',
    kun_reading: ['め'],
    on_reading: ['もく'],
    han_viet: 'MỤC',
    meaning_vi: 'mắt',
    meaning_en: 'eye',
    radicals: '目',
    strokes: 5,
    level: 'N5',
    examples: [
      {
        sentence: '目が痛いです。',
        reading: 'めがいたいです。',
        meaning_vi: 'Mắt tôi đau.',
        meaning_en: 'My eyes hurt.',
      },
      {
        sentence: '本の目次を見てください。',
        reading: 'ほんのもくじをみてください。',
        meaning_vi: 'Hãy xem mục lục của cuốn sách.',
        meaning_en: 'Please check the table of contents of the book.',
      },
    ],
  },
  {
    kanji: '友',
    kun_reading: ['とも'],
    on_reading: ['ゆう'],
    han_viet: 'HỮU',
    meaning_vi: 'bạn',
    meaning_en: 'friend',
    radicals: '又',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '私の友達はとても優しいです。',
        reading: 'わたしのともだちはとてもやさしいです。',
        meaning_vi: 'Bạn bè của tôi rất tốt bụng.',
        meaning_en: 'My friends are very kind.',
      },
      {
        sentence: '彼は私の友人です。',
        reading: 'かれはわたしのゆうじんです。',
        meaning_vi: 'Anh ấy là bạn thân của tôi.',
        meaning_en: 'He is my close friend.',
      },
    ],
  },
  {
    kanji: '来',
    kun_reading: ['く.る', 'きた.る', 'きた.す'],
    on_reading: ['らい'],
    han_viet: 'LAI',
    meaning_vi: 'đến, tới',
    meaning_en: 'come',
    radicals: '木',
    strokes: 7,
    level: 'N5',
    examples: [
      {
        sentence: '彼は明日来ます。',
        reading: 'かれはあしたきます。',
        meaning_vi: 'Anh ấy sẽ đến vào ngày mai.',
        meaning_en: 'He will come tomorrow.',
      },
      {
        sentence: '将来は医者になりたいです。',
        reading: 'しょうらいはいしゃになりたいです。',
        meaning_vi: 'Tôi muốn trở thành bác sĩ trong tương lai.',
        meaning_en: 'I want to become a doctor in the future.',
      },
    ],
  },
  {
    kanji: '立',
    kun_reading: ['た.つ', 'た.てる'],
    on_reading: ['りつ'],
    han_viet: 'LẬP',
    meaning_vi: 'đứng, thiết lập',
    meaning_en: 'stand, establish',
    radicals: '立',
    strokes: 5,
    level: 'N5',
    examples: [
      {
        sentence: '彼は席を立ちました。',
        reading: 'かれはせきをたちました。',
        meaning_vi: 'Anh ấy đã đứng dậy khỏi chỗ ngồi.',
        meaning_en: 'He stood up from his seat.',
      },
    ],
  },
  {
    kanji: '六',
    kun_reading: ['む.つ', 'むい'],
    on_reading: ['ろく'],
    han_viet: 'LỤC',
    meaning_vi: 'số sáu',
    meaning_en: 'six',
    radicals: '八',
    strokes: 4,
    level: 'N5',
    examples: [
      {
        sentence: '私は六冊の本を持っています。',
        reading: 'わたしはろくさつのほんをもっています。',
        meaning_vi: 'Tôi có sáu cuốn sách.',
        meaning_en: 'I have six books.',
      },
    ],
  },
  {
    kanji: '話',
    kun_reading: ['はなし', 'はな.す'],
    on_reading: ['わ'],
    han_viet: 'THOẠI',
    meaning_vi: 'nói, nói chuyện, câu chuyện',
    meaning_en: 'talk, conversation',
    radicals: '言',
    strokes: 13,
    level: 'N5',
    examples: [
      {
        sentence: '彼とよく話します。',
        reading: 'かれとよくはなします。',
        meaning_vi: 'Tôi thường nói chuyện với anh ấy.',
        meaning_en: 'I often talk with him.',
      },
      {
        sentence: '面白い話を聞きました。',
        reading: 'おもしろいはなしをききました。',
        meaning_vi: 'Tôi đã nghe một câu chuyện thú vị.',
        meaning_en: 'I heard an interesting story.',
      },
    ],
  },
];
